package cyf.es.search.domain;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import java.util.Date;

/**
 * Created by yufei on 2017/5/21.
 */
public class TMInfo {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_reg_nbr
     *
     * @mbggenerated
     */
    private String tmRegNbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_type
     *
     * @mbggenerated
     */
    private String tmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_cn
     *
     * @mbggenerated
     */
    private String tmCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_en
     *
     * @mbggenerated
     */
    private String tmEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_wd
     *
     * @mbggenerated
     */
    private String tmWd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_digit
     *
     * @mbggenerated
     */
    private String tmDigit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.trial_period
     *
     * @mbggenerated
     */
    private String trialPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.reg_period
     *
     * @mbggenerated
     */
    private String regPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_applicant
     *
     * @mbggenerated
     */
    private String tmApplicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_agent
     *
     * @mbggenerated
     */
    private String tmAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_area
     *
     * @mbggenerated
     */
    private String tmArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_desc
     *
     * @mbggenerated
     */
    private String tmDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.expiry_date
     *
     * @mbggenerated
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.reg_date
     *
     * @mbggenerated
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_address
     *
     * @mbggenerated
     */
    private String tmAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_class
     *
     * @mbggenerated
     */
    private Integer tmClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.app_date
     *
     * @mbggenerated
     */
    private String appDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.inter_reg_date
     *
     * @mbggenerated
     */
    private String interRegDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.trial_date
     *
     * @mbggenerated
     */
    private String trialDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.is_total
     *
     * @mbggenerated
     */
    private String isTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.grace_begin_date
     *
     * @mbggenerated
     */
    private Date graceBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.grace_end_date
     *
     * @mbggenerated
     */
    private Date graceEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.renew_begin_date
     *
     * @mbggenerated
     */
    private Date renewBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.renew_end_date
     *
     * @mbggenerated
     */
    private Date renewEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.ggDate
     *
     * @mbggenerated
     */
    private Date ggdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_applicant_en
     *
     * @mbggenerated
     */
    private String tmApplicantEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.markName
     *
     * @mbggenerated
     */
    private String markname;

    private String tmAddressEn;

    /**
     *中文同音
     */
    private String tmTy;
    /**
     *中文多音
     */
    private String tmDy;

    public String getTmTy() {
        return tmTy;
    }

    public void setTmTy(String tmTy) {
        this.tmTy = tmTy;
    }

    public String getTmDy() {
        return tmDy;
    }

    public void setTmDy(String tmDy) {
        this.tmDy = tmDy;
    }

    public String getTmAddressEn() {
        return tmAddressEn;
    }

    public void setTmAddressEn(String tmAddressEn) {
        this.tmAddressEn = tmAddressEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.id
     *
     * @return the value of t_tm_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.id
     *
     * @param id the value for t_tm_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_reg_nbr
     *
     * @return the value of t_tm_detail.tm_reg_nbr
     *
     * @mbggenerated
     */
    public String getTmRegNbr() {
        return tmRegNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_reg_nbr
     *
     * @param tmRegNbr the value for t_tm_detail.tm_reg_nbr
     *
     * @mbggenerated
     */
    public void setTmRegNbr(String tmRegNbr) {
        this.tmRegNbr = tmRegNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_type
     *
     * @return the value of t_tm_detail.tm_type
     *
     * @mbggenerated
     */
    public String getTmType() {
        return tmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_type
     *
     * @param tmType the value for t_tm_detail.tm_type
     *
     * @mbggenerated
     */
    public void setTmType(String tmType) {
        this.tmType = tmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_cn
     *
     * @return the value of t_tm_detail.tm_cn
     *
     * @mbggenerated
     */
    public String getTmCn() {
        return tmCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_cn
     *
     * @param tmCn the value for t_tm_detail.tm_cn
     *
     * @mbggenerated
     */
    public void setTmCn(String tmCn) {
        this.tmCn = tmCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_en
     *
     * @return the value of t_tm_detail.tm_en
     *
     * @mbggenerated
     */
    public String getTmEn() {
        return tmEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_en
     *
     * @param tmEn the value for t_tm_detail.tm_en
     *
     * @mbggenerated
     */
    public void setTmEn(String tmEn) {
        this.tmEn = tmEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_wd
     *
     * @return the value of t_tm_detail.tm_wd
     *
     * @mbggenerated
     */
    public String getTmWd() {
        return tmWd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_wd
     *
     * @param tmWd the value for t_tm_detail.tm_wd
     *
     * @mbggenerated
     */
    public void setTmWd(String tmWd) {
        this.tmWd = tmWd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_digit
     *
     * @return the value of t_tm_detail.tm_digit
     *
     * @mbggenerated
     */
    public String getTmDigit() {
        return tmDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_digit
     *
     * @param tmDigit the value for t_tm_detail.tm_digit
     *
     * @mbggenerated
     */
    public void setTmDigit(String tmDigit) {
        this.tmDigit = tmDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.trial_period
     *
     * @return the value of t_tm_detail.trial_period
     *
     * @mbggenerated
     */
    public String getTrialPeriod() {
        return trialPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.trial_period
     *
     * @param trialPeriod the value for t_tm_detail.trial_period
     *
     * @mbggenerated
     */
    public void setTrialPeriod(String trialPeriod) {
        this.trialPeriod = trialPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.reg_period
     *
     * @return the value of t_tm_detail.reg_period
     *
     * @mbggenerated
     */
    public String getRegPeriod() {
        return regPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.reg_period
     *
     * @param regPeriod the value for t_tm_detail.reg_period
     *
     * @mbggenerated
     */
    public void setRegPeriod(String regPeriod) {
        this.regPeriod = regPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_applicant
     *
     * @return the value of t_tm_detail.tm_applicant
     *
     * @mbggenerated
     */
    public String getTmApplicant() {
        return tmApplicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_applicant
     *
     * @param tmApplicant the value for t_tm_detail.tm_applicant
     *
     * @mbggenerated
     */
    public void setTmApplicant(String tmApplicant) {
        this.tmApplicant = tmApplicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_agent
     *
     * @return the value of t_tm_detail.tm_agent
     *
     * @mbggenerated
     */
    public String getTmAgent() {
        return tmAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_agent
     *
     * @param tmAgent the value for t_tm_detail.tm_agent
     *
     * @mbggenerated
     */
    public void setTmAgent(String tmAgent) {
        this.tmAgent = tmAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_area
     *
     * @return the value of t_tm_detail.tm_area
     *
     * @mbggenerated
     */
    public String getTmArea() {
        return tmArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_area
     *
     * @param tmArea the value for t_tm_detail.tm_area
     *
     * @mbggenerated
     */
    public void setTmArea(String tmArea) {
        this.tmArea = tmArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_desc
     *
     * @return the value of t_tm_detail.tm_desc
     *
     * @mbggenerated
     */
    public String getTmDesc() {
        return tmDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_desc
     *
     * @param tmDesc the value for t_tm_detail.tm_desc
     *
     * @mbggenerated
     */
    public void setTmDesc(String tmDesc) {
        this.tmDesc = tmDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.create_time
     *
     * @return the value of t_tm_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.create_time
     *
     * @param createTime the value for t_tm_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.expiry_date
     *
     * @return the value of t_tm_detail.expiry_date
     *
     * @mbggenerated
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.expiry_date
     *
     * @param expiryDate the value for t_tm_detail.expiry_date
     *
     * @mbggenerated
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.reg_date
     *
     * @return the value of t_tm_detail.reg_date
     *
     * @mbggenerated
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.reg_date
     *
     * @param regDate the value for t_tm_detail.reg_date
     *
     * @mbggenerated
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_address
     *
     * @return the value of t_tm_detail.tm_address
     *
     * @mbggenerated
     */
    public String getTmAddress() {
        return tmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_address
     *
     * @param tmAddress the value for t_tm_detail.tm_address
     *
     * @mbggenerated
     */
    public void setTmAddress(String tmAddress) {
        this.tmAddress = tmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_class
     *
     * @return the value of t_tm_detail.tm_class
     *
     * @mbggenerated
     */
    public Integer getTmClass() {
        return tmClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_class
     *
     * @param tmClass the value for t_tm_detail.tm_class
     *
     * @mbggenerated
     */
    public void setTmClass(Integer tmClass) {
        this.tmClass = tmClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.app_date
     *
     * @return the value of t_tm_detail.app_date
     *
     * @mbggenerated
     */
    public String getAppDate() {
        return appDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.app_date
     *
     * @param appDate the value for t_tm_detail.app_date
     *
     * @mbggenerated
     */
    public void setAppDate(String appDate) {
        this.appDate = appDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.inter_reg_date
     *
     * @return the value of t_tm_detail.inter_reg_date
     *
     * @mbggenerated
     */
    public String getInterRegDate() {
        return interRegDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.inter_reg_date
     *
     * @param interRegDate the value for t_tm_detail.inter_reg_date
     *
     * @mbggenerated
     */
    public void setInterRegDate(String interRegDate) {
        this.interRegDate = interRegDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.trial_date
     *
     * @return the value of t_tm_detail.trial_date
     *
     * @mbggenerated
     */
    public String getTrialDate() {
        return trialDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.trial_date
     *
     * @param trialDate the value for t_tm_detail.trial_date
     *
     * @mbggenerated
     */
    public void setTrialDate(String trialDate) {
        this.trialDate = trialDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.is_total
     *
     * @return the value of t_tm_detail.is_total
     *
     * @mbggenerated
     */
    public String getIsTotal() {
        return isTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.is_total
     *
     * @param isTotal the value for t_tm_detail.is_total
     *
     * @mbggenerated
     */
    public void setIsTotal(String isTotal) {
        this.isTotal = isTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.grace_begin_date
     *
     * @return the value of t_tm_detail.grace_begin_date
     *
     * @mbggenerated
     */
    public Date getGraceBeginDate() {
        return graceBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.grace_begin_date
     *
     * @param graceBeginDate the value for t_tm_detail.grace_begin_date
     *
     * @mbggenerated
     */
    public void setGraceBeginDate(Date graceBeginDate) {
        this.graceBeginDate = graceBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.grace_end_date
     *
     * @return the value of t_tm_detail.grace_end_date
     *
     * @mbggenerated
     */
    public Date getGraceEndDate() {
        return graceEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.grace_end_date
     *
     * @param graceEndDate the value for t_tm_detail.grace_end_date
     *
     * @mbggenerated
     */
    public void setGraceEndDate(Date graceEndDate) {
        this.graceEndDate = graceEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.renew_begin_date
     *
     * @return the value of t_tm_detail.renew_begin_date
     *
     * @mbggenerated
     */
    public Date getRenewBeginDate() {
        return renewBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.renew_begin_date
     *
     * @param renewBeginDate the value for t_tm_detail.renew_begin_date
     *
     * @mbggenerated
     */
    public void setRenewBeginDate(Date renewBeginDate) {
        this.renewBeginDate = renewBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.renew_end_date
     *
     * @return the value of t_tm_detail.renew_end_date
     *
     * @mbggenerated
     */
    public Date getRenewEndDate() {
        return renewEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.renew_end_date
     *
     * @param renewEndDate the value for t_tm_detail.renew_end_date
     *
     * @mbggenerated
     */
    public void setRenewEndDate(Date renewEndDate) {
        this.renewEndDate = renewEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.ggDate
     *
     * @return the value of t_tm_detail.ggDate
     *
     * @mbggenerated
     */
    public Date getGgdate() {
        return ggdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.ggDate
     *
     * @param ggdate the value for t_tm_detail.ggDate
     *
     * @mbggenerated
     */
    public void setGgdate(Date ggdate) {
        this.ggdate = ggdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_applicant_en
     *
     * @return the value of t_tm_detail.tm_applicant_en
     *
     * @mbggenerated
     */
    public String getTmApplicantEn() {
        return tmApplicantEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_applicant_en
     *
     * @param tmApplicantEn the value for t_tm_detail.tm_applicant_en
     *
     * @mbggenerated
     */
    public void setTmApplicantEn(String tmApplicantEn) {
        this.tmApplicantEn = tmApplicantEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.markName
     *
     * @return the value of t_tm_detail.markName
     *
     * @mbggenerated
     */
    public String getMarkname() {
        return markname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.markName
     *
     * @param markname the value for t_tm_detail.markName
     *
     * @mbggenerated
     */
    public void setMarkname(String markname) {
        this.markname = markname;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tm_similar_group
     *
     * @mbggenerated
     */
    private String tmSimilarGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.tmdetail
     *
     * @mbggenerated
     */
    private String tmdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tm_detail.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tm_similar_group
     *
     * @return the value of t_tm_detail.tm_similar_group
     *
     * @mbggenerated
     */
    public String getTmSimilarGroup() {
        return tmSimilarGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tm_similar_group
     *
     * @param tmSimilarGroup the value for t_tm_detail.tm_similar_group
     *
     * @mbggenerated
     */
    public void setTmSimilarGroup(String tmSimilarGroup) {
        this.tmSimilarGroup = tmSimilarGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.tmdetail
     *
     * @return the value of t_tm_detail.tmdetail
     *
     * @mbggenerated
     */
    public String getTmdetail() {
        return tmdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.tmdetail
     *
     * @param tmdetail the value for t_tm_detail.tmdetail
     *
     * @mbggenerated
     */
    public void setTmdetail(String tmdetail) {
        this.tmdetail = tmdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tm_detail.status
     *
     * @return the value of t_tm_detail.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tm_detail.status
     *
     * @param status the value for t_tm_detail.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }


    private Integer pageCnt;

    private Integer rowStart; // 起始行

    private Integer totalCnt; // 总记录数

    public Integer getPageCnt() {
        return pageCnt;
    }

    public void setPageCnt(Integer pageCnt) {
        this.pageCnt = pageCnt;
    }

    public Integer getRowStart() {
        return rowStart;
    }

    public void setRowStart(Integer rowStart) {
        this.rowStart = rowStart;
    }

    public Integer getTotalCnt() {
        return totalCnt;
    }

    public void setTotalCnt(Integer totalCnt) {
        this.totalCnt = totalCnt;
    }

    /*
    private Integer tmClass;

    private String tmCn;

    private String tmEn;

    private String tmApplicant;

    private Integer id;

    private String tmdetail;

    private String tmRegNbr;

    private Integer pageCnt;

    private Integer rowStart; // 起始行

    private Integer totalCnt; // 总记录数


    public String getTmEn() {
        return tmEn;
    }

    public void setTmEn(String tmEn) {
        this.tmEn = tmEn;
    }

    public Integer getTmClass() {
        return tmClass;
    }

    public void setTmClass(Integer tmClass) {
        this.tmClass = tmClass;
    }

    public String getTmCn() {
        return tmCn;
    }

    public void setTmCn(String tmCn) {
        this.tmCn = tmCn;
    }

    public String getTmApplicant() {
        return tmApplicant;
    }

    public void setTmApplicant(String tmApplicant) {
        this.tmApplicant = tmApplicant;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTmdetail() {
        return tmdetail;
    }

    public void setTmdetail(String tmdetail) {
        this.tmdetail = tmdetail;
    }

    public String getTmRegNbr() {
        return tmRegNbr;
    }

    public void setTmRegNbr(String tmRegNbr) {
        this.tmRegNbr = tmRegNbr;
    }

    public Integer getPageCnt() {
        return pageCnt;
    }

    public void setPageCnt(Integer pageCnt) {
        this.pageCnt = pageCnt;
    }

    public Integer getRowStart() {
        return rowStart;
    }

    public void setRowStart(Integer rowStart) {
        this.rowStart = rowStart;
    }

    public Integer getTotalCnt() {
        return totalCnt;
    }

    public void setTotalCnt(Integer totalCnt) {
        this.totalCnt = totalCnt;
    }*/
}
